### ISSUE TITLE
neo-cli v2.5.0+ doesn't create blocks anymore

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-privatenet-docker#15]
This issue is for tracking the current issue that neo-cli >= v2.5.0 doesn't create blocks anymore.

This is the output of neo-cli version 2.4.1 (current in this master branch, and last neo-cli version that works):

    $ ./docker_build.sh

    $ ./docker_run.sh
    Starting container...
    f76bb5849ead5f991b90cfe9f05aef182df6637aa700a3f422cb6bbe6f5bdcb1

    $ docker exec -it neo-privnet /bin/bash

    root@neo-privnet:/# screen -ls
    There are screens on:
        39.node4	(12/14/17 15:12:26)	(Detached)
        26.node3	(12/14/17 15:12:26)	(Detached)
        11.node2	(12/14/17 15:12:26)	(Detached)
        8.node1	(12/14/17 15:12:26)	(Detached)
    4 Sockets in /var/run/screen/S-root.
    root@neo-privnet:/# screen -d -r 11.node2

This is the output inside the screen:

    spawn dotnet neo-cli.dll --rpc
    NEO-CLI Version: 2.4.1.0

    neo> open wallet wallet2.db3
    open wallet wallet2.db3
    password: two
    ***
    neo> start consensus
    start consensus
    [15:14:06] OnStart
    [15:14:06] initialize: height=1 view=0 index=0 role=Backup
    [15:14:11] OnPrepareRequestReceived: height=1 view=0 index=1 tx=1
    [15:14:11] send perpare response
    [15:14:11] OnPrepareResponseReceived: height=1 view=0 index=2
    [15:14:11] relay block: 0xa868990dc63031d2fc12ff344778e88341461ccd187f1e876a69ad511121af96
    [15:14:11] persist block: 0xa868990dc63031d2fc12ff344778e88341461ccd187f1e876a69ad511121af96
    [15:14:11] initialize: height=2 view=0 index=0 role=Backup

---

When running the latest neo-cli (eg neo-cli 2.5.2 from this branch: https://github.com/CityOfZion/neo-privatenet-docker/tree/252), with the same initial commands as above, this is the output inside the screen:

    spawn dotnet neo-cli.dll --rpc
    NEO-CLI Version: 2.5.2.0

    neo> open wallet wallet2.db3
    open wallet wallet2.db3
    password: ***
    neo> start consensus
    [11:03:36] OnStart

And it just hangs there without generating blocks.

**Comment by AshRolls** [comment]
Feedback from @erikzhang 
>[4:08 PM] erik: You need to add the consensus contract to the wallet"

**Comment by metachris** [comment]
What's the steps to add the consensus contracts to the wallets?

**Comment by AshRolls** [comment]
Not entirely sure... once we figure it out we should be able to just recreate the supplied wallet files with the consensus contract included.

**Comment by metachris** [comment]
Fixed with #18
