### ISSUE TITLE
No gas from the contract after multisig created

### ISSUE THREAD

**Issue by mcb345** [CityOfZion/neo-privatenet-docker#45]
Hi I cannot receive any GAS/NEO after the chain is up, I tried following this exact step on getting GAS/NEO http://docs.neo.org/en-us/network/private-chain.html , no luck I still have 0 on my wallet

**Comment by metachris** [comment]
Have you tried the image here: https://hub.docker.com/r/cityofzion/neo-privatenet/

Works there to send/receive NEO and GAS. If you want to build the privnet from scratch, you need to transfer the initial funds out like here: https://github.com/CityOfZion/neo-privatenet-docker/blob/master/scripts/claim_neo_and_gas_fixedwallet.py
