### ISSUE TITLE
MAC: neopy cmd shows container nut running.

### ISSUE THREAD

**Issue by aaroncatalano** [CityOfZion/neo-privatenet-docker#47]
Followed City of Zion instructions for setting up private net and container. ./docker_build.sh does not run on MAC with zion build.  Getting errors.  Error: private network container doesn't seem to be running, or RPC is not enabled.

Says Linux only.  Is the CityofZion project only meant to be running on Windows? If so this should be stated in Prerequisites.

**Comment by metachris** [comment]
Can you post the full output? Works on macos for me.

**Comment by aaroncatalano** [comment]
(base) Aarons-MacBook-Pro:neo-privatenet-docker aaroncatalano$ ./docker_build.sh
Using downloaded neo-cli v2.7.4
- downloading https://github.com/neo-project/neo-cli/releases/download/v2.7.4/neo-cli-linux-x64.zip...
./docker_build.sh: line 50: wget: command not found

I am on mac running from terminal.

**Comment by aaroncatalano** [comment]
Issue resolved: Docker repository file has only Linux and Windows instances.  To install NEO-CLI on MAC you must follow these hidden instructions: http://docs.neo.org/en-us/node/cli/publish.html
