### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by Phenomenan** [CityOfZion/neo-privatenet-docker#50]
I'm new to neo developing. I'm trying to pull the privatenet for the first time using 
`docker pull cityofzion/neo-privatenet`
but it's been 5 hours and terminal stuck at extracting. Sorry for my bad English. I am using mac os. Is this normal? or should I restart it?

**Comment by metachris** [comment]
Just restart, the problem seems to be either at Docker hub or your connection.
