### ISSUE TITLE
update to neo-cli 2.9.0

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-privatenet-docker#55]
The image is still on `2.7.6` whereas `2.9.0` is [out](https://github.com/neo-project/neo-cli/tree/v2.9.0)
It would be nice to have a docker image with the latest version that supports things like stack isolation and the `map` contract parameter

**Comment by metachris** [comment]
2.9.0 has broken RPC. I'd say only going to update once this version works properly

**Comment by ixje** [comment]
ugh that sucks. Did you create an issue on the NEO project? If not, can you describe the issue so I can make a report. I'm in need of a 2.9.0 environment :(

**Comment by metachris** [comment]
No I haven't seen an issue, just reports on Discord. Perhaps @hal0x2328 can help here, I think he has encountered it in practice.
