### ISSUE TITLE
privenet docker_run_and_create_wallet.sh problem

### ISSUE THREAD

**Issue by mlabbaf** [CityOfZion/neo-privatenet-docker#56]
I try to use docker_run_and_create_wallet.sh script. Based on the README it's typical to have some internal errors during its execution. 
However I got some errors that seems fatal and prohibit me to use it. 
It includes failed to extract from json file and insufficient fund for asset id. 

I attach the running log and I will be appreciated if anyone can give me any idea about solving the problem.

Thanks in advance

[log.txt](https://github.com/CityOfZion/neo-privatenet-docker/files/2449819/log.txt)

**Comment by metachris** [comment]
Please retry now with latest master branch, and create a new issue if the problem persists. (fixed with latest commit)
