### ISSUE TITLE
claim script incompatible with new neo-python release

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-privatenet-docker#64]
The claim_neo_and_gas script doesn't work anymore with the new neo-python release. Here's the claim script: https://github.com/CityOfZion/neo-privatenet-docker/blob/master/scripts/claim_neo_and_gas_fixedwallet.py

The error is 

    Traceback (most recent call last):
      File "/neo-python/claim_neo_and_gas_fixedwallet.py", line 43, in <module>
        from neo.Prompt.Commands.LoadSmartContract import ImportMultiSigContractAddr
    ImportError: cannot import name 'ImportMultiSigContractAddr'

Currently I've updated the [Dockerfile](https://github.com/CityOfZion/neo-privatenet-docker/blob/master/Dockerfile#L41) to use neo-python v0.8.2. If you want to work at this, comment this line to use the master branch of neo-python.

**Comment by nunojusto** [comment]
The question is, after last commit, does multisig got broken?
Because @LysanderGG did the fix correctly... but it doesn't work.
