### ISSUE TITLE
I pulled the Docker image and used it, but I can not synchronize the wallet.

### ISSUE THREAD

**Issue by okayu8** [CityOfZion/neo-privatenet-docker#68]
Hello. Please do not hesitate to contact me because my private network connection is not good.

I docker pull Ver: 2.9.1 image and use it.
https://hub.docker.com/r/cityofzion/neo-privatenet?ref=login

After I run the image, I copy the local Smart contract to the container and erase the old block chain data.

```
docker cp localFilePath / compileSmartContract.avm neo-privatenet: /neo-python/filename.avm
rm -rf /root/.neopython/Chains/privnet*
```
Then start the interface with the `neopy` command.

When opening the wallet with the following command and checking the wallet with the wallet command, it seems that it is "percent_synced": 0 "and it is not possible to synchronize the wallet.
`open wallet neo-privnet.wallet`

Progress of PriveteNet is displayed as 1/1.
If you connect immediately after PC start up, you may be able to synchronize well in rare cases.

Do you know for why this phenomenon is caused? Thank you very much.

neo-privatenet ver: 2.9.1
Docker Desktop ver: Version 2.0.0.0-win81 (29211)
OS: Windows10

**Comment by nunojusto** [comment]
Please, can you explain what you did to erase the old block chain data?

**Comment by okayu8** [comment]
@nunojusto 
I executed the following command in the container for deletion of old block chain.
`rm -rf /root/.neopython/Chains/privnet*`
